# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78807be75ddff5655c20e7fbb629eb0e72af2567b51b1dec705e8dadba7d5a1a1b338c8b80be77d2ee1c304fe18263b399a70d022ab81b484d835726f891487a

test:
  secret_key_base: 40c5250181399d15848aec8b994df5f7191055f60a65f71727a89e7d41450f603f2d3638b0858774564fc06e6274b1e9f2c09f5f3dccefca3315d9e8025a19e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
